# Pipeline to Pull Task Definition JSON, Run Falcon Container Sensor Patch Utility and Register New Task with ECS.

# Required Variables
# AWS_ACCOUNT_ID
# AWS_REGION
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# FALCON_CID
# FALCON_CONTAINER_SENSOR_REGISTRY

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
  displayName: 'Install Docker'

- bash: |
    wget https://raw.githubusercontent.com/ryanjpayne/cs-container-security/main/AWS%20ECS/azure-devops/dummy-task.json -P /tmp/
    sed -i "s/<AWS_ACCOUNT_ID>/$(AWS_ACCOUNT_ID)/" /tmp/dummy-task.json
    sed -i "s/<AWS_REGION>/$(AWS_REGION)/" /tmp/dummy-task.json
  displayName: 'Retrieve ECS Task Spec File and Set AWS Parameters'

- bash: |
    aws ecr get-login-password --region $(AWS_REGION) | sudo docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com
    export PULL_TOKEN=$(echo "{\"auths\":{\"$(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com\":{\"auth\": \"$(echo AWS:$(aws ecr get-login-password)|base64 -w 0)\"}}}" | base64 -w 0) 
    echo "##vso[task.setvariable variable=PULL_TOKEN]$PULL_TOKEN"
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
  displayName: 'Create a Pull Token for ECR'

- bash: |
    sudo docker run -v /tmp/:/var/run/spec \
    --rm "$(FALCON_CONTAINER_SENSOR_REGISTRY)" \
    -cid "$(FALCON_CID)" \
    -image "$(FALCON_CONTAINER_SENSOR_REGISTRY)" \
    -pulltoken $(PULL_TOKEN) \
    -ecs-spec-file /var/run/spec/dummy-task.json > /tmp/patched-dummy-task.json
  displayName: 'Run Falcon Patching Utility on ECS Task Spec File'

- bash: |
    sudo cat /tmp/patched-dummy-task.json
  displayName: 'Print Patched Task Spec File'

- bash: |
    cd /tmp
    aws ecs register-task-definition --cli-input-json file://dummy-task.json
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
  displayName: 'Register Patched ECS Task'